install: warn rather than exit upon failure when updating rubygems (#2612)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -207,7 +207,9 @@ check_ruby_version() {
 check_rubygems() {
 	if command_exists gem${RUBYSUFFIX}; then
 		info 'Updating rubygems...'
-		sudo gem${RUBYSUFFIX} update --system
+		if ! sudo gem${RUBYSUFFIX} update --system; then
+			warn "Updating rubygems failed"
+		fi
 	fi
 }
 
